import type { MetricSnapshot, RevenueDurabilityScore } from "./metrics";

/**
 * Shared margin knobs for contribution LTV and payback math.
 *
 * `contributionMarginPct` expresses **retained** dollars per revenue dollar after COGS and variable selling costs
 * (payment fees, pick/pack, shipping subsidies) using a single MVP lever.
 */
export interface MarginAssumptions {
  /** Retained share of net revenue on average (0–1). Example: 0.35 => 35¢ contribution per $1. */
  contributionMarginPct: number;
  /** Optional override when net revenue already backs out discounts/refunds — defaults to 1 in calculators. */
  netRevenueMultiplier?: number;
}

/** User-tunable levers for transparent what-if exploration — no probabilistic forecasting in MVP. */
export interface ScenarioInput {
  /** Baseline reference the engine already computed. */
  baseline?: MetricSnapshot;
  marginAssumptions?: MarginAssumptions;
  /** Relative delta applied to modeled repeat / first-to-second conversion (semantics per calculator). */
  repeatRateDelta?: number;
  /** Multiplicative or absolute AOV shift — caller documents interpretation. */
  avgOrderValueDelta?: number;
  /** Relative CAC shift for acquisition efficiency scenarios. */
  cacDelta?: number;
  /** Target payback guardrail (months) used to score feasibility, not to auto-optimize. */
  paybackTargetMonths?: number;
  /** How far LTV curves extend when comparing contribution outcomes. */
  contributionLtvHorizonMonths?: number;
}

/** Scenario deltas against baseline suitable for cards and tables. */
export interface ScenarioOutput {
  projectedRevenueDelta?: number;
  projectedContributionLtv?: number;
  projectedLtvCac?: number;
  projectedPaybackMonths?: number | null;
  durability?: RevenueDurabilityScore;
  /** Short explanation of dominant lever — generated by rules layer, not this type alone. */
  headlineSummary?: string;
}
